#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     ArmLowerLimit,  sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Runtest_Arm()
{
	eraseDisplay();
	nxtDisplayTextLine(3, "ArmDemo");
	//saving motor properties
	int PIDMode = nMotorPIDSpeedCtrl[Arm];
	bool bBrakeMode = bFloatDuringInactiveMotorPWM;
	//changing motor properties
	nMotorPIDSpeedCtrl[Arm] = mtrSpeedReg;
	bFloatDuringInactiveMotorPWM = false;

	while(nNxtButtonPressed != 03)
	{
	 if(nNxtButtonPressed == 2)
	 {
	  	nxtDisplayTextLine(2, "Left Pressed");
	  	if((SensorValue[ArmLowerLimit]) > 45)
	  			motor[Arm] = 0;
	  		else
	      	motor[Arm] = -35;
		}
	 else if(nNxtButtonPressed == 1)
	 {
	 		nxtDisplayTextLine(2, "Right Pressed");
	 		motor[Arm] = 60;
	 }
	 else if(nNxtButtonPressed == -1)
	 {
	    nxtDisplayTextLine(2, "None Pressed");
	    motor[Arm] = 0;
	 }
	 wait1Msec(500);
	}
	// restoring motor properties
	nMotorPIDSpeedCtrl[Arm] = PIDMode;
	bFloatDuringInactiveMotorPWM = bBrakeMode;
}

void Runtest_Slider()
{
	eraseDisplay();
	nxtDisplayTextLine(3, "SliderTest");
	nMotorEncoder[Slider] = 0;
	while (nNxtButtonPressed != 3)
	{
		if (nNxtButtonPressed == 2)
		{
			nxtDisplayTextLine(2, "Left Pressed");
			motor[Slider] = 100;
		}
		else if(nNxtButtonPressed == 1)
	 	{
	 		nxtDisplayTextLine(2, "Right Pressed");
	 		motor[Slider] = -100;
	 	}
	 	else if(nNxtButtonPressed == -1)
	 	{
	    nxtDisplayTextLine(2, "None Pressed");
	   	motor[Slider] = 0;
	 	}
	 	wait1Msec(500);
	}
}

task main()
{
	while(nNxtButtonPressed != 0)
	{
		nxtDisplayTextLine(2, "Run Demo");
		nxtDisplayTextLine(3, "Exit Program");
		if (nNxtButtonPressed == 0)
		{
			break;
		}
		else if (nNxtButtonPressed == 3)
		{
			nNxtButtonPressed = 0;
			Runtest_Arm();
		 /*Runtest_Slider();*/

		}
	 	wait1Msec(500);

	}

}
