#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "ServoLibrary.c"
#include "JoystickDriver.c"

#define RightHookUnlock 220
#define RightHookLock 125
#define LeftHookUnlock 20
#define LeftHookLock 128

void UnlockRightHook() //Function that unlocks the right hook
{
	ServoRotate(RightHook, RightHookUnlock);
}
void LockRightHook() //Function that Locks the right hook
{
	ServoRotate(RightHook, RightHookLock);
}
void UnlockLeftHook() //Function that unlocks the left hook
{
	ServoRotate(LeftHook, LeftHookUnlock);
}
void LockLeftHook() //Function that Locks the left hook
{
	ServoRotate(LeftHook, LeftHookLock);
}

void Move(int MtrPwr_Left, int MtrPwr_Right, int MtrDur_Left, int MtrDur_Right) //Move function which takes power for left side and
{																																							  //right side, duration
 	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[RightDrive] = 0;

 	nMotorEncoderTarget[LeftDrive] = -MtrDur_Left;
 	nMotorEncoderTarget[RightDrive] = -MtrDur_Right;

 	motor[LeftDrive] = MtrPwr_Left;
 	motor[RightDrive] = MtrPwr_Right;

 	while ( (nMotorRunState[LeftDrive] != runStateIdle) &&
   	     	(nMotorRunState[RightDrive] != runStateIdle) )
 	{
   	//wait
 	}

 	motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
}

void initializeRobot() //Function which will setup the robot for autonomous (raise hooks and keep block thrower up)
{
	LockRightHook();
	LockLeftHook();

	bFloatDuringInactiveMotorPWM = false;

	nMotorEncoder[LeftDrive] = 0;//Reset encoders for drivetrain motors
	nMotorEncoder[RightDrive] = 0;

	ServoRotate(AutonomousBlock, 240);

  return;
}

task main()
{
		//use NXT buttons to select autonomous route and time delay

		//bDisplayDiagnostics = false;   // Disable diagnostic display
		initializeRobot();

  	waitForStart(); // Wait for the beginning of autonomous phase.
		UnlockRightHook();
		UnlockLeftHook();
		//wait1Msec(15000);
		int LeftIRVal = HTIRS2readACDir(LeftIR); //Initialize variable storing left IR sensor value

		nMotorEncoder[RightDrive] = 0;
		int timeElapsed = 0; //define variable timeElapsed which will store time values
		time1[T1] = 0; //reset the robot's internal timer
    timeElapsed = time1[T1]; //set time elapsed to the timer value

    motor[LeftDrive] = 30;
		motor[RightDrive] = 30;
		wait10Msec(5);

		while(LeftIRVal != 6) //move forward until robot is perpendicular to IR beacon
		{
			motor[LeftDrive] = 70;
			motor[RightDrive] = 70;
			wait10Msec(1);

			LeftIRVal = HTIRS2readACDir(LeftIR); //refresh the current IR value
		}
		motor[LeftDrive] = 0; //Brake Motors
		motor[RightDrive] = 0;

		timeElapsed = time1[T1] - timeElapsed; //Calculate how long the robot moved to reach the baskets.

		/*wait1Msec(1000);
		if(nMotorEncoder[RightDrive] > 3000){
			motor[LeftDrive] = -70;
			motor[RightDrive] = -70;
			wait1Msec(1500);
			motor[LeftDrive] = 0; //Brake Motors
			motor[RightDrive] = 0;
		}*/

		ServoRotate (AutonomousBlock,30); //Rotating Servo to put block in basket
		ServoRotate (AutonomousBlock,130);//Rotate Servo inside robot

		//nxtDisplayCenteredTextLine(3, "%d", nMotorEncoder[RightDrive]);//display current encoder values for drive train motors on screen

		motor[LeftDrive] = -70;
		motor[RightDrive] = -70;
		wait1Msec(timeElapsed);

		motor[LeftDrive] = 0; //Brake Motors
		motor[RightDrive] = 0;

		while(1){wait10Msec(10);} //wait until end of autonomous time period
}
