#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    BasketTiltL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    BasketTiltR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "ServoLibrary.c"

unsigned int StartWait = 0;

void initializeRobot() //Function which will setup the robot for autonomous
                       //(collapse hooks and lower autonomous arm)
{
	disableDiagnosticsDisplay();

	LockRightHook();
	LockLeftHook();
	StartTask(ResetBasket);

	bFloatDuringInactiveMotorPWM = false;

	ServoRotate(AutonomousBlock, 240);

	while(nNxtButtonPressed != 3)
	{
		if(nNxtButtonPressed == 1)
			StartWait = StartWait + 1000;
		else if (nNxtButtonPressed == 2)
			if(StartWait > 0)
				StartWait = StartWait - 1000;
		else
		{
			//Do nothing
		}
		nxtDisplayCenteredTextLine(0, "%d ms delay", StartWait);
		wait1Msec(400);
	}

	bDisplayDiagnostics = true;

  return;
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

 	wait1Msec(StartWait);
 	PlaySound(soundBeepBeep);

	motor[Arm] = 45;//Raise arm for safe navigation over ramp. This is so that the bottom of the end effector does not hit the
	wait1Msec(500); //bump at the bottom of the ramp.
	motor[Arm] = 0;
  motor[LeftDrive] = -100; //Go backwards for a timed amount, when
	motor[RightDrive] = -100;//the robot reaches the ramp
	wait1Msec(2350);
	motor[LeftDrive] = 0; //Stop the robot
	motor[RightDrive] = 0;


  UnlockRightHook(); //Release hooks, raise block arm so they
	UnlockLeftHook();  //don't get in way of teleop
	ServoRotate(AutonomousBlock, 240);

  while(1){wait10Msec(10);}
}
