#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*/////////////////*/
//Include Libraries//
/*/////////////////*/

#include "drivers/hitechnic-irseeker-v2.h"
#include "ServoLibrary.c"
#include "JoystickDriver.c"

/*/////////////////*/
//Macros for Servos//
/*/////////////////*/

#define RightHookUnlock 220
#define RightHookLock 125
#define LeftHookUnlock 20
#define LeftHookLock 128

void UnlockRightHook() //Function that unlocks the right hook
{
	ServoRotate(RightHook, RightHookUnlock);
}

void LockRightHook() //Function that Locks the right hook
{
	ServoRotate(RightHook, RightHookLock);
}

void UnlockLeftHook() //Function that unlocks the left hook
{
	ServoRotate(LeftHook, LeftHookUnlock);
}

void LockLeftHook() //Function that Locks the left hook
{
	ServoRotate(LeftHook, LeftHookLock);
}

void Move(int MtrPwr_Left, int MtrPwr_Right, int MtrDur_Left, int MtrDur_Right) //Move function which takes power for left side and
{																																							  //right side, duration
 	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[RightDrive] = 0;

 	nMotorEncoderTarget[LeftDrive] = -MtrDur_Left;
 	nMotorEncoderTarget[RightDrive] = -MtrDur_Right;

 	motor[LeftDrive] = MtrPwr_Left;
 	motor[RightDrive] = MtrPwr_Right;

 	while ( (nMotorRunState[LeftDrive] != runStateIdle) &&
   	     	(nMotorRunState[RightDrive] != runStateIdle) )
 	{
   	//wait
 	}

 	motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
}

void initializeRobot() //Function which will setup the robot for autonomous (raise hooks and keep block thrower up)
{

	LockRightHook();
	LockLeftHook();

	bFloatDuringInactiveMotorPWM = false;

	nMotorEncoder[LeftDrive] = 0;//Reset encoders for drivetrain motors
	nMotorEncoder[RightDrive] = 0;

	ServoRotate(AutonomousBlock, 200);

  return;
}

task main()
{
		//use NXT buttons to select autonomous route and time delay

		initializeRobot();

  	waitForStart(); // Wait for the beginning of autonomous phase.
		UnlockRightHook();
		UnlockLeftHook();
		int LeftIRVal = HTIRS2readACDir(LeftIR); //Initialize variable storing left IR sensor value



		int timeElapsed = 0; //define variable timeElapsed which will store time values
		wait10Msec(500);
		time1[T1] = 0; //reset the timer
		timeElapsed = time1[T1] //set time elapsed to the timer value
		while(LeftIRVal != 5) //move forward until robot is perpendicular to IR beacon
		{
			motor[LeftDrive] = 100;
			motor[RightDrive] = 100;
			wait10Msec(1);

			LeftIRVal = HTIRS2readACDir(LeftIR); //refresh the current IR value
		}
		timeElapsed = time1[T1] - timeElapsed;
			motor[LeftDrive] = 0; //Brake Motors
			motor[RightDrive] = 0;

		nxtDisplayCenteredTextLine(3, "%d", nMotorEncoder[RightDrive]);//display current encoder values for drive train motors on screen

		////////////////////////////
		//deploy autonomous block://
		////////////////////////////

		//Move(70, 70, 1000, 1000);
		if(timeElapsed < 1500) // if time elapsed to find beacon is less than 2000 ms, then probably we mov a little more
		{
				motor[LeftDrive] = 50;
				motor[RightDrive] = 50;
				wait1Msec(350);
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
		}
		else //Else just deploy right there
		{
				motor[LeftDrive] = 0;
				motor[RightDrive] = 0;
		}
		ServoRotate (AutonomousBlock,30); //Rotating Servo to put block in basket
		ServoRotate (AutonomousBlock,31);
		ServoRotate (AutonomousBlock,130);//Rotate Servo inside robot

		wait10Msec(10);

		/////////////////
		//go onto ramp://
		/////////////////

		while(1)
		{
			if(nMotorEncoder[RightDrive] < 500) // Go forward until a certain total distance is reached
			{
				motor[RightDrive] = 70;
			  motor[LeftDrive] = 70;
			}
			else //once that distance is reached, stop the robot
			{
				motor[RightDrive] = 0;
	 			motor[LeftDrive] = 0;
	 		}
		}

		Move(-60, 60, 2150, 2150);  //turn robot so that backside faces ramp
		Move(60, 60, 3100, 3100);   //Move forward toward ramp
		Move(-60, 60, 2150, 2150);  //Turn perpendicular to ramp
		Move(100, 100, 4000, 4000); //Drive on to ramp at full force

		motor[RightDrive] = 0; //stop robot and park on ramp
 		motor[LeftDrive] = 0;

		while(1){wait10Msec(10);} //wait until end of autonomous time period
}
