#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ServoLibrary.c"

#define AutonomousBlockIn 239
#define AutonomousBlockInit 200
#define AutonomousBlockOut 70

void AutonomousBlockIn()
{
	ServoRotate(AutonomousBlock, AutonomousBlockIn);
}

void AutonomousBlockInit()
{
	ServoRotate(AutonomousBlock, AutonomousBlockInit);
}

void AutonomousBlockOut()
{
	ServoRotate(AutonomousBlock, AutonomousBlockOut);
}

task main()
{
while(1){
AutonomousBlockIn();
wait10Msec(200);
AutonomousBlockInit();
wait10Msec(200);
AutonomousBlockOut();
wait10Msec(200);

}
