#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMtr,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMtr,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "ServoLibrary.c"

void Move(int MtrPwr_Left, int MtrPwr_Right, int MtrDur_Left, int MtrDur_Right)
{
 	nMotorEncoder[LeftMtr] = 0;
	nMotorEncoder[RightMtr] = 0;

 	nMotorEncoderTarget[LeftMtr] = -MtrDur_Left;
 	nMotorEncoderTarget[RightMtr] = -MtrDur_Right;

 	motor[LeftMtr] = MtrPwr_Left;
 	motor[RightMtr] = MtrPwr_Right;

 	while ( (nMotorRunState[LeftMtr] != runStateIdle) &&
   	     	(nMotorRunState[RightMtr] != runStateIdle) )
 	{
   	//wait
 	}

 	motor[LeftMtr] = 0;
  motor[RightMtr] = 0;
}

task main()
{
		//use NXT buttons to select autonomous route and time delay

		nMotorEncoder[RightMtr] = 0;//Reset encoders for drivetrain motors
		nMotorEncoder[LeftMtr] = 0;

		int LeftIRVal = HTIRS2readACDir(LeftIR); //Initialize variable storing left IR sensor value


		while(LeftIRVal != 5) //move forward until robot is next to IR beacon
		{
			motor[RightMtr] = 70;
			motor[LeftMtr] = 70;
			wait10Msec(1);

			LeftIRVal = HTIRS2readACDir(LeftIR);
		}
		motor[RightMtr] = 0;
		motor[LeftMtr] = 0;

		nxtDisplayCenteredTextLine(3, "%d", nMotorEncoder[RightMtr]);//display current encoder values for drive train motors on screen

		//deploy autonomous block
		ServoReset0(AutonomousBlock); //Setting Servo to 0 position
		ServoRotate (AutonomousBlock,110); //Rotating Servo to put block in basket

		wait10Msec(10);

		//go onto ramp
		while(nMotorEncoder[RightMtr] < 8200){
			motor[RightMtr] = 70;
			motor[LeftMtr] = 70;
			wait10Msec(1);
		}

		motor[RightMtr] = 0;
 		motor[LeftMtr] = 0;

 		Move(-60, 60, 2150, 2150);
		Move(60, 60, 3100, 3100);
		Move(-60, 60, 2150, 2150);
		Move(100, 100, 4000, 4000);

		while(1){wait10Msec(10);}
}
