#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    BasketTiltL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    BasketTiltR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "ServoLibrary.c"
#include "JoystickDriver.c"
#include "Move_Library.c"

unsigned int StartWait = 0;


void initializeRobot() //Function which will setup the robot for autonomous (raise hooks and keep block thrower up)
{
	// Set DSP mode to 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;

 	disableDiagnosticsDisplay();

	StartTask(ResetBasket);
	LockRightHook();
	LockLeftHook();

	bFloatDuringInactiveMotorPWM = false;

	nMotorEncoder[LeftDrive] = 0;//Reset encoders for drivetrain motors
	nMotorEncoder[RightDrive] = 0;

	ServoRotate(AutonomousBlock, 240);

	while(nNxtButtonPressed != 3)
	{
		if(nNxtButtonPressed == 1)
			StartWait = StartWait + 1000;
		else if (nNxtButtonPressed == 2)
			if(StartWait > 0)
				StartWait = StartWait - 1000;
		else
		{
			//Do nothing
		}
		nxtDisplayCenteredTextLine(0, "%d ms delay", StartWait);
		wait1Msec(400);
	}

	bDisplayDiagnostics = true;

	return;
}
task main()
{
	//use NXT buttons to select autonomous route and time delay

	//bDisplayDiagnostics = false;   // Disable diagnostic display
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	wait1Msec(StartWait);
	PlaySound(soundBeepBeep);

	//UnlockRightHook();
	//UnlockLeftHook();

	Move(-70, -70, 700, 700);
	ServoRotate (AutonomousBlock,30); //Rotating Servo to put block in basket
	ServoRotate (AutonomousBlock,130);//Rotate Servo inside robot
	Move(-70, -70, 4100, 4100);
	Move(70, -70, 1700, 1700);
	motor[Arm] = 45;//Raise arm for safe navigation over ramp. This is so that the bottom of the end effector does not hit the
	wait1Msec(300); //bump at the bottom of the ramp.
	motor[Arm] = 0;
	Move(-100, -100, 4500, 4500);

	ServoRotate(AutonomousBlock, 240);
}
