#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    cServo,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position01,            110, 128, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CSERVO_FULLSPEED_REV	0
#define CSERVO_STOP		127
#define CSERVO_FULLSPEED_FWD	256


task main()
{


while (true)
  {
	    //If the left button is pressed on the nxt, move the arm down
	    if(nNxtButtonPressed == 2)
	  	{
	  		servo[cServo] = CSERVO_FULLSPEED_REV;
	    }
	    	    //If the right button is pressed on the nxt, move the arm up
	    else if(nNxtButtonPressed == 1)
	 		{
	  		servo[cServo] = CSERVO_FULLSPEED_FWD;
	    }
	    //If no buttons on the NXT are pressed, dont move the arm
	    else if(nNxtButtonPressed == -1)
	    {
	      servo[cServo] = CSERVO_STOP;
	    }
	    wait10Msec(1);
	 }
}
