#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot() //Function which prepares robot for Tele-Op
{

 	return;
}

task main();
{
	initializeRobot();
	waitForStart();   // wait for start of tele-op phase

	int MtrPwrLeftDrive = 0;    //Power for Left drive
	int MtrPwrRightDrive = 0;   //Power for Right Drive

	while(1)
	{
		alive();
		getJoystickSettings(joystick);

		//Handle Drive Train Power Settings For the Two Joysticks
		float LeftJoyPwr = ((joystick.joy1_y1) * 0.71825);
		float RightJoyPwr   = ((joystick.joy1_y2) * 0.71825);

		//If the Value Given By the Joysticks is too low to Move the Drive Train, Set the Power to 0
		if(abs(RightJoyPwr) <= 15)
			RightJoyPwr = 0;
		if(abs(LeftJoyPwr) <= 15)
			LeftJoyPwr = 0;

		//Setting Power for Drive Train
		if(joy1Btn(4) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = 100;
				MtrPwrLeftDrive = 100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = 75;
				MtrPwrLeftDrive = 75;
			}
			else
			{
				MtrPwrRightDrive = 30;
				MtrPwrLeftDrive = 30;
			}
		}
		else if(joy1Btn(2) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = -100;
				MtrPwrLeftDrive = -100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = -75;
				MtrPwrLeftDrive = -75;
			}
			else
			{
				MtrPwrRightDrive = -30;
				MtrPwrLeftDrive = -30;
			}
		}
		else if(joy1Btn(1) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = 100;
				MtrPwrLeftDrive = -100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = 75;
				MtrPwrLeftDrive = -75;
			}
			else
			{
				MtrPwrRightDrive = 40;
				MtrPwrLeftDrive = -40;
			}
		}
		else if(joy1Btn(3) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = -100;
				MtrPwrLeftDrive = 100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = -75;
				MtrPwrLeftDrive = 75;
			}
			else
			{
				MtrPwrRightDrive = -40;
				MtrPwrLeftDrive = 40;
			}
		}
		//If No Buttons Are Pressed, Move The Robot According to the Joysticks

		else

		{
			MtrPwrLeftDrive = LeftJoyPwr;
			MtrPwrRightDrive = RightJoyPwr;
		}

		motor[RightMotor] = MtrPwrRightDrive;
		motor[LeftMotor] = MtrPwrLeftDrive;

		wait1Msec(10);
	}
}
