#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     ArmLowerLimit,  sensorLightActive)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    BasketTiltL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    BasketTiltR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BASKET_R_NO_TILT	2
#define BASKET_L_NO_TILT	250
#define BASKET_R_TILT	122
#define BASKET_L_TILT	130

#include "ServoLibrary.c"

void TiltBasketDown()
{
	TwoServoRotate(BasketTiltR, BasketTiltL,
								BASKET_R_TILT, BASKET_L_TILT);
}

void ResetBasket()
{
	TwoServoRotate(BasketTiltR, BasketTiltL,
								BASKET_R_NO_TILT, BASKET_L_NO_TILT);
}

task main()
{
	motor[Arm] = 60;
  wait1Msec(200);
  motor[Arm] = 0;
  while (true)
  {
	    //If the left button is pressed on the nxt, move the arm down
	    if(nNxtButtonPressed == 2)
	  	{
	  		TiltBasketDown();
	  		motor[RotorL] = -100;
				motor[RotorR] = -100;
	    }

	    	    //If the right button is pressed on the nxt, move the arm up
	    else if(nNxtButtonPressed == 1)
	 		{
	 				motor[RotorL] = 100;
					motor[RotorR] = 100;

	    }
	    //If no buttons on the NXT are pressed, dont move the arm
	    else if(nNxtButtonPressed == -1)
	    {
	    	ResetBasket();
	      motor[RotorL] = 0;
				motor[RotorR] = 0;

	    }
	    wait1Msec(5);
	 }
}
