#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    BasketTiltL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    BasketTiltR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*/////////////////*/
//Include Libraries//
/*/////////////////*/

task main()
{

	bFloatDuringInactiveMotorPWM = false;

  while (true)
  {
	    //If the left button is pressed on the nxt, move the arm down
	    if(nNxtButtonPressed == 2)
	  	{
	  		motor[RightDrive] = 75;
	  		motor[LeftDrive] = 75;
	    }
	    	    //If the right button is pressed on the nxt, move the arm up
	    else if(nNxtButtonPressed == 1)
	 		{
	  		motor[RightDrive] = -75;
	  		motor[LeftDrive] = -75;
	    }
	    //If no buttons on the NXT are pressed, dont move the arm
	    else if(nNxtButtonPressed == -1)
	    {
	      motor[RightDrive] = 0;
	  		motor[LeftDrive] = 0 ;
	    }
	    wait1Msec(5);
	 }
}
