



#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     RightMtr,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LeftMtr,       tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroLib.c"

task main()
{
	while(true) {getHeading();}
	//startTask(CalcHeading)
}
