#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     SlideLift1,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     SlideLift2,    tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-touchmux.h"

const tMUXSensor HTEOPD = msensor_S2_1;
const tMUXSensor IR_right = msensor_S2_2;
const tMUXSensor IR_left = msensor_S2_3;

#define SlideLift_Touch 2
#define ArticArm_Touch 3

task main()
{
//bFloatDuringInactiveMotorPWM = false;  // the motors will NOT coast when power is not applied
	nMotorPIDSpeedCtrl[SlideLift1] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[SlideLift2] = mtrSpeedReg;
  while (true)
  {
	    //If the left button is pressed on the nxt, move the arm down
	    if(nNxtButtonPressed == 2)
	  	{
	      motor[SlideLift1] = -100;
	    	motor[SlideLift2] = -100;
	    }
	    	    //If the right button is pressed on the nxt, move the arm up
	    else if(nNxtButtonPressed == 1)
	 		{
	      motor[SlideLift1] = 100;
	    	motor[SlideLift2] = 100;
	    }
	    //If no buttons on the NXT are pressed, dont move the arm
	    else if(nNxtButtonPressed == -1)
	    {
	      motor[SlideLift1] = 0;
	    	motor[SlideLift2] = 0;
	    }
	    wait10Msec(1);
	 }
}
