#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     ArmLowerLimit,  sensorLightActive)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-superpro.h"

int StepOne()
{
	int initialValue;
	HTSPBsetupIO(HTSPB, 0x00);
	initialValue = HTSPBreadIO(HTSPB, 0xff);

	return initialValue;
}

task main()
{
	Step_1_all_inputs_are_zero();
	Step_2_even_num_port_are_inputs_and_drive_zero_n_one_to_all_odd_number_outports();
	Step_3_odd_num_port_are_inputs_and_drive_zero_n_one_to_all_even_number_outports();
	Test_4_LEDs_One_Led_At_A_Time();
  Test_IR_switches(); // First program IR ports as output ports.
}
