#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// AFOOFA 2013 Block Party Robot Configuration
// NXT S1 --> Motor Ctrl1 --> Motor Ctrl2 --> Motor Ctrl3 --> Servo Ctrl1
// Motor Controller 1
// 		port1 - Right side motors (ganged two motors)
// 		Port2 - Left side motors (ganged two motors)
// Motor Controller 2
// 		port1 - Articulating Arm
// 		Port2 - Sliders (ganged two motors)
// Motor Controller 3
// 		port1 - Flag 1
// 		Port2 - not connected
// Servo Controller 1
// 		Ch1 - Right Hook lock
// 		Ch2 - Left Hook lock
//    Ch3 -
//    Ch4 -
// 		Ch5 -
// 		Ch6 -

task main()
{
	// test right side motors
	motor[RightDrive] = 75;
	wait10Msec(20);
	motor[RightDrive] = 0;
	motor[RightDrive] = -75;
	wait10Msec(20);
	motor[RightDrive] = 0;

	// test left side motors
	motor[LeftDrive] = 75;
	wait10Msec(20);
	motor[LeftDrive] = 0;
	motor[LeftDrive] = -75;
	wait10Msec(20);
	motor[LeftDrive] = 0;

	// test pullup motors
/*	motor[Slider] = 75;
	wait10Msec(20);
	motor[Slider] = 0;
	motor[Slider] = -75;
	wait10Msec(20);
	motor[Slider] = 0;
	*/

	// test flag motor
	motor[Flag] = 75;
	wait10Msec(20);
	motor[Flag] = 0;
	motor[Flag] = -75;
	wait10Msec(20);
	motor[Flag] = 0;

	// test arm motor
/*	motor[Arm] = 60;
	wait10Msec(20);
	motor[Arm] = 0;
	*/
	/*motor[Arm] = -60;
	wait10Msec(10);
	motor[Arm] = 0;*/


}
