#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          Flag1,         tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Flag2,         tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Turntable,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     Rotor,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Pullup,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Container,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//bool taskEntered = false;

void StopDriveMotors()
{
	 	motor[LeftDrive] = 0;
		motor[RightDrive] = 0;
}

task main()
{
	//initializeRobot();
  waitForStart();   // wait for start of tele-op phase

	//nMotorEncoder[Right] = 0;
	//nMotorEncoder[Left] = 0;

  int MtrPwrLeftDrive = 0;
	int MtrPwrRightDrive = 0;
	int MtrPwrTurntable = 0;
	int MtrPwrArm = 0;
	int MtrPwrRotor = 0;
	int MtrPwrPullup = 0;

	while(1)
	{
			alive();
			getJoystickSettings(joystick);

			//Handle Drive Train Power Settings For the Two Joysticks
			float RightJoyPwr = ((joystick.joy1_y1) * 0.78125);
			float LeftJoyPwr = ((joystick.joy1_y2) * 0.78125);

			//If the Value Given By the Joysticks is too low to Move the Drive Train, Set the Power to 0
			if(abs(RightJoyPwr) <= 20)
					RightJoyPwr = 0;
			if(abs(LeftJoyPwr) <= 20)
					LeftJoyPwr = 0;

			//Setting Power for Drive Train
			if(joy1Btn(4) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightDrive = 40;
					MtrPwrLeftDrive = 40;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightDrive = 75;
					MtrPwrLeftDrive = 75;
				}
				else
			  {
			  	MtrPwrRightDrive = 100;
					MtrPwrLeftDrive = 100;
			  }
			}
			else if(joy1Btn(2) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightDrive = -40;
					MtrPwrLeftDrive = -40;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightDrive = -75;
					MtrPwrLeftDrive = -75;
				}
				else
			  {
			  	MtrPwrRightDrive = -100;
					MtrPwrLeftDrive = -100;
			  }
			}
			else if(joy1Btn(1) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightDrive = 40;
					MtrPwrLeftDrive = -40;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightDrive = 75;
					MtrPwrLeftDrive = -75;
				}
				else
			  {
			  	MtrPwrRightDrive = 100;
					MtrPwrLeftDrive = -100;
			  }
			}
			else if(joy1Btn(3) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightDrive = -40;
					MtrPwrLeftDrive = 40;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightDrive = -75;
					MtrPwrLeftDrive = 75;
				}
				else
			  {
			  	MtrPwrRightDrive = -100;
					MtrPwrLeftDrive = 100;
			  }
			}
		 	//If No Buttons Are Pressed, Move The Robot According to the Joysticks
			else
		  {
				MtrPwrLeftDrive = LeftJoyPwr;
				MtrPwrRightDrive = RightJoyPwr;
		  }

		  //Setting Power for Rotor
		  if(joy1Btn(5) == 1)
		  {
		  	MtrPwrRotor = 100;
		  }
		  else if(joy1Btn(6) == 1)
		  {
		  	MtrPwrRotor = -100;
		  }
		  else
		  {
		  	MtrPwrRotor = 0;
		  }

		  //Setting Power for Turntable
		  if(joy2Btn(3) == 1)
		  {
		  	if(joy2Btn(9) == 1)
				{
					MtrPwrTurntable = 50;
				}
				else
			  {
			  	MtrPwrTurntable = 100;
			  }
		  }
		  else if(joy2Btn(1) == 1)
		  {
		  	if(joy2Btn(9) == 1)
				{
					MtrPwrTurntable = -50;
				}
				else
			  {
			  	MtrPwrTurntable = -100;
			  }
		  }
		  else
		  {
		  	MtrPwrTurntable = 0;
		  }

		  //Setting Power for Arm
		  if(joy2Btn(4) == 1)
		  {
		  	if(joy2Btn(9) == 1)
				{
					MtrPwrArm = 50;
				}
				if(joy2Btn(10) == 1)
				{
					MtrPwrArm = 75;
				}
				else
			  {
			  	MtrPwrArm = 100;
			  }
		  }
		  else if(joy2Btn(2) == 1)
		  {
		  	if(joy2Btn(9) == 1)
				{
					MtrPwrArm = -50;
				}
				if(joy2Btn(10) == 1)
				{
					MtrPwrArm = -75;
				}
				else
			  {
			  	MtrPwrArm = -100;
			  }
		  }
		  else
		  {
		  	MtrPwrArm = 0;
		  }

		  //Setting Power for Pullup
		  if(joy2Btn(5) == 1)
		  {
		  	MtrPwrPullup = 100;
		  }
		  else if(joy2Btn(6) == 1)
		  {
		  	MtrPwrPullup = -100;
		  }
		  else
		  {
		  	MtrPwrPullup = 0;
		  }

		  //Settng Power for Pullup Hook (SERVO)
		  //
		  //

		  //Setting Power for Container (SERVO)
		  //
		  //

		  //Set Power to Motors
		  motor[RightDrive] = MtrPwrRightDrive;
		  motor[LeftDrive] = MtrPwrLeftDrive;
		  motor[Turntable] = MtrPwrTurntable;
		  motor[Arm] = MtrPwrArm;
		  motor[Rotor] = MtrPwrRotor;
		  motor[Pullup] = MtrPwrPullup;

		  //Set Power to Servos
		  //
		  //

			wait1Msec(50);
	}
}
