#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LeftIR,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          RotorR,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          RotorL,        tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Slider,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutonomousBlock,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    BasketTiltL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    BasketTiltR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*/////////////////*/
//Include Libraries//
/*/////////////////*/

#include "JoystickDriver.c"
#include "ServoLibrary.c"
#include "drivers/hitechnic-superpro.h"
#include "Move_Library.c"

#include "rdpartyrobotcdr-3.3.1\drivers\hitechnic-sensormux.h"
#include "drivers/lego-light.h"

#define PULLUP_PRESET 10000

//const tMUXSensor NoSensor1 = msensor_S3_1;
//const tMUXSensor NoSensor2 = msensor_S3_2;
const tMUXSensor Gyro = msensor_S3_3;
const tMUXSensor ArmLowerLimit = msensor_S3_4;

//#pragma config(Sensor, S3,     ArmLowerLimit,  sensorLightActive)
bool bSliderGoingUp = false;
bool autoRotorOn = false;


task RaiseSliderToPulllup()
{
   UnlockRightHook();
	 UnlockLeftHook();
//	nMotorEncoder[Slider] = 0;
 while (abs(nMotorEncoder[Slider])<  PULLUP_PRESET)
 {
    motor[Slider] = -100;
  	wait1Msec(2);
 }
 motor[Slider] = 0;
 bSliderGoingUp = false;
}


//***************************************************/
/* Task to sense if the Block Container is Full***** Uses IR Sharp distance GP2Y0D805 Switches mounted
	the front side of	left and right block containers.
   Block containers are two blocks deep. IR switches
   are mounted in such a way to detect the presense
   of front block. This indicates block container is
   full.
*/
//***************************************************/
/*
task BlockContainerFull()
{
  // makes B4 digital port an output.
  HTSPBsetupIO(HTSPB, 0xFf); //B4 through B7 are output ports; rest are all input ports
  ubyte LEDOutMask = 0;

while(1){

		LEDOutMask = LEDOutMask & 0xf0; // Set LED display mask

	// Display LEDs
	 HTSPBwriteIO(HTSPB, 0xff);

    //wait1Msec(25);
  }
}
*/

task BlockContainerFull()
{
  // makes B4 digital port an output.
  HTSPBsetupIO(HTSPB, 0xF0); //B4 through B7 are output ports; rest are all input ports
  ubyte LEDOutMask = 0;

while(1){

  // Read B0 port - B0 is connected IR switch
	if(HTSPBreadIO(HTSPB, 0x02) == 0) // if B1 is clear then there is block in front it.
			LEDOutMask = LEDOutMask | 0x30; // Set LED display mask
	else
			LEDOutMask = LEDOutMask & 0xc0; // Set LED display mask
  // Read B1 port - B1 is connected to IR Switch
	if(HTSPBreadIO(HTSPB, 0x01) == 0) // if B0 is clear then there is block in front it.
		LEDOutMask = LEDOutMask | 0xC0; // Set LED display mask

	else
		LEDOutMask = LEDOutMask & 0x30; // Set LED display mask

	// Display LEDs
	 HTSPBwriteIO(HTSPB, LEDOutMask);

    wait1Msec(25);
  }
}

void initializeRobot() //Function which prepares robot for Tele-Op
{
	// Reset Encores
	nMotorEncoder[RightDrive] = 0;
	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[Arm] = 0;
	nMotorEncoder[Slider] = 0;
	LockRightHook();
	LockLeftHook();
	// Kick off the Block Contaner Full detect task
	StartTask(BlockContainerFull);
	StartTask(ResetBasket);

	ServoRotate(AutonomousBlock, 230);

	return;
}

task main()
{
	// init the Robot
	initializeRobot();
	waitForStart();   // wait for start of tele-op phase

	// Declare variables
	int MtrPwrLeftDrive = 0;    //Power for Left drive
	int MtrPwrRightDrive = 0;   //Power for Right Drive
	int MtrPwrArm = 0;          //Articulating arm Power
	int MtrPwrRotorL= 0;        //Left Rotor Power
	int MtrPwrRotorR= 0;        //Right Rotor Power
	int MtrPwrSlider = 0;       //Pull-Up Slider Power
	int MtrPwrFlag = 0;         //Flag power
	bool RotorControlBy1 = false;//Rotor overwrite variable
	//int ServoDirection = 0;     //Direction which servo will rotate
	//nMotorPIDSpeedCtrl[LeftDrive] = mtrSpeedReg;
	//nMotorPIDSpeedCtrl[RightDrive] = mtrSpeedReg;
	//nMotorPIDSpeedCtrl[Arm] = mtrSpeedReg;
	bFloatDuringInactiveMotorPWM = false;


	// Turn the light on
  LSsetActive(ArmLowerLimit);

	while(1)
	{
		alive();
		getJoystickSettings(joystick);

		//Handle Drive Train Power Settings For the Two Joysticks
		float LeftJoyPwr = ((joystick.joy1_y1) * 0.71825);
		float RightJoyPwr   = ((joystick.joy1_y2) * 0.71825);
		RotorControlBy1 = false;
		//If the Value Given By the Joysticks is too low to Move the Drive Train, Set the Power to 0
		if(abs(RightJoyPwr) <= 20)
			RightJoyPwr = 0;
		if(abs(LeftJoyPwr) <= 20)
			LeftJoyPwr = 0;

		//Setting Power for Drive Train
		if(joy1Btn(4) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = 100;
				MtrPwrLeftDrive = 100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = 75;
				MtrPwrLeftDrive = 75;
			}
			else
			{
				MtrPwrRightDrive = 30;
				MtrPwrLeftDrive = 30;
			}
		}
		else if(joy1Btn(2) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = -100;
				MtrPwrLeftDrive = -100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = -75;
				MtrPwrLeftDrive = -75;
			}
			else
			{
				MtrPwrRightDrive = -30;
				MtrPwrLeftDrive = -30;
			}
		}
		else if(joy1Btn(1) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = 100;
				MtrPwrLeftDrive = -100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = 75;
				MtrPwrLeftDrive = -75;
			}
			else
			{
				MtrPwrRightDrive = 40;
				MtrPwrLeftDrive = -40;
			}
		}
		else if(joy1Btn(3) == 1)
		{
			if(joy1Btn(9) == 1)
			{
				MtrPwrRightDrive = -100;
				MtrPwrLeftDrive = 100;
			}
			else if(joy1Btn(10) == 1)
			{
				MtrPwrRightDrive = -75;
				MtrPwrLeftDrive = 75;
			}
			else
			{
				MtrPwrRightDrive = -40;
				MtrPwrLeftDrive = 40;
			}
		}
		//If No Buttons Are Pressed, Move The Robot According to the Joysticks
		else
		{
			MtrPwrLeftDrive = LeftJoyPwr;
			MtrPwrRightDrive = RightJoyPwr;
		}

		//Setting Power for Rotor
		// Rotors are controlled by both controllers.
		// Controller 1 Driver is expected use only for dispensing.
		// Controller 2 Driver is expected to use if only for Collecting.
		if(joy2Btn(10) == 1)
		{
			MtrPwrRotorL = 100;
			MtrPwrRotorR = 100;
			autoRotorOn = true;
		}


		if((joy1Btn(5) == 1) ||
			(joystick.joy2_y1 > 30))
		{
			autoRotorOn = false;
			MtrPwrRotorL = 100;
		}
		else if((joy1Btn(7) == 1) ||
			     (joystick.joy2_y1 < -30))
		{
			autoRotorOn = false;
			MtrPwrRotorL = -100;
		}
		else
		{
			if(autoRotorOn == false)
				MtrPwrRotorL = 0;
		}
		if((joy1Btn(6) == 1) ||
			(joystick.joy2_y2 > 30))
		{
			autoRotorOn = false;
			MtrPwrRotorR = 100;
		}
		else if((joy1Btn(8) == 1) ||
			     (joystick.joy2_y2 < -30))
		{
			autoRotorOn = false;
			MtrPwrRotorR = -100;
		}
		else
		{
			if(autoRotorOn == false)
				MtrPwrRotorR = 0;
		}

		//Setting Power for Flag
		if(joy2Btn(5) == 1)
		{
			MtrPwrFlag = 100;
		}
		else if(joy2Btn(6) == 1)
		{
			MtrPwrFlag = -100;
		}
		else
		{
			MtrPwrFlag = 0;
		}

		//Setting Power for Arm
		if(joy2Btn(3) == 1) // raise the arm
		{
			nMotorPIDSpeedCtrl[LeftDrive] = mtrNoReg;
			MtrPwrArm = 75;
		}
		else if(joy2Btn(1) == 1)// lower the arm
		{
			 nMotorPIDSpeedCtrl[Arm] = mtrSpeedReg;
			// We employed Light sensor to check lower limt
			// this avoid over run of arm motor
			if(LSvalNorm(ArmLowerLimit) > 45)
			{
				MtrPwrArm = 0;
        nMotorPIDSpeedCtrl[LeftDrive] = mtrNoReg;
			}
			else
				MtrPwrArm = -60;
		}
		else
		{
			MtrPwrArm = 0;
		}

		//Setting Power for Slider
		// First, see if preset positino button is pressed.
		// Pressent button 8 goes to pull-up hight. However
		// we have incorporated the override for preset position.
		// While slider is going up in response to Preset button  (8)
		// Pressing manual control buttons  4 or 2, would stop the
		// automated preset move and manual control take over.
		if((joy2Btn(7) == 1) && (bSliderGoingUp == false))
		{
			// Start the task to raise the slider to pull up postion.
			StartTask(RaiseSliderToPulllup);
			bSliderGoingUp = true; // set the flag to say that Slider is going up
			//wait1Msec(500);
		}
		else if(joy2Btn(4) == 1) // override to manual control.
		{
			if(bSliderGoingUp == true) // if Auto preset move has begun..d
			{
					motor[Slider] = 0; // stop the motor to stop auto control
		   		StopTask(RaiseSliderToPulllup); //stop the task
		   		bSliderGoingUp = false; // set the flat to indicate that slider no logner going up
			}
			MtrPwrSlider = -100; //set the manual power value for slider
		}
		else if(joy2Btn(2) == 1)
		{
			if(bSliderGoingUp == true) //override to manual control when button 2 is pressed
			{
					motor[Slider] = 0;
		   		StopTask(RaiseSliderToPulllup);
		   		bSliderGoingUp = false;
			}
			MtrPwrSlider = 100;
		}
		else
		{
			MtrPwrSlider = 0;
		}


		if((joy2Btn(8) == 1) ||
			(joystick.joy1_TopHat == 0))
		{
				autoRotorOn = false;
				StartTask(TiltBasketDown);
				MtrPwrRotorL = -100;
				MtrPwrRotorR = -100;

		}
		else if ( (joy2Btn(8) == 0) ||
						(joystick.joy1_TopHat == -1 ))
		{
			StartTask(ResetBasket);
		//	MtrPwrRotorL = 0;
		//	MtrPwrRotorR = 0;

		}


/*		//Setting Preset Positions for Arm
		if(joy2Btn(7) == 1)
		{
			while(nMotorEncoder[Arm] < 1000){
				motor[Arm] = 50;
				wait1Msec(10);
			}
			motor[Arm] = 0;
		}
	*/

		motor[RightDrive] = MtrPwrRightDrive;
		motor[LeftDrive] = MtrPwrLeftDrive;
		motor[Arm] = MtrPwrArm;
		motor[RotorL] = MtrPwrRotorL;
		motor[RotorR] = MtrPwrRotorR;
		if(bSliderGoingUp == false) // set the manual power only if slider in not auto move to preset-postion
			motor[Slider] = MtrPwrSlider;
		motor[Flag] = MtrPwrFlag;
		wait1Msec(10);
	}

}
