#pragma config(Sensor, S3,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.3.1\drivers\hitechnic-sensormux.h"
#include "drivers/lego-light.h"

const tMUXSensor LEGOLS = msensor_S3_4;

task main() {
	// Turn the light on
  LSsetActive(LEGOLS);
}
