#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FLAG_SERVO_STOP1  servo (FlagServo1) = 127;
#define FLAG_UP_SERVO_FWD1  servo (FlagServo1) = 256;
#define FLAG_DOWN_SERVO_REV1 servo (FlagServo1) = 0;

#define FLAG_SERVO_STOP2  servo (FlagServo2) = 127;
#define FLAG_UP_SERVO_FWD2  servo (FlagServo2) = 256;
#define FLAG_DOWN_SERVO_REV2 servo (FlagServo2) = 0;

#define FLAG_SERVO_STOP3  servo (FlagServo3) = 127;
#define FLAG_UP_SERVO_FWD3  servo (FlagServo3) = 256;
#define FLAG_DOWN_SERVO_REV3 servo (FlagServo3) = 0;

task main()
{

 FLAG_DOWN_SERVO_REV1
 FLAG_DOWN_SERVO_REV2
 FLAG_DOWN_SERVO_REV3

 while(1)
 {
   wait10Msec(1);
 }

}
